<?xml version="1.0"?>
<package format="3">
  <name>devrob_waypoints</name>
  <version>0.0.1</version>
  <description>DevRob waypoint demo using MoveIt2 and Panda arm</description>

  <maintainer email="koyaneniyaswanth@gmail.com">yash</maintainer>
  <license>MIT</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Runtime & build dependencies -->
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>moveit_ros_planning_interface</depend>

  <!-- yaml-cpp is a system library used via CMake find_package(yaml-cpp) -->
  <exec_depend>yaml-cpp</exec_depend>

  <!-- Test deps (optional, you can keep them) -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
